name: Daily CVE Fetch

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  fetch-cves:
    runs-on: ubuntu-latest

    steps:
      - name: Clone CVE List
        run: |
          git clone https://github.com/CVEProject/cvelistV5/ --filter=blob:none --no-checkout
          cd cvelistV5
          git ls-tree -r main --name-only | egrep "CVE-[[:digit:]]{4}-[[:digit:]]+" -o > cves.txt
      
      - name: Upload CVEs
        uses: actions/upload-artifact@v3
        with:
          name: cves
          path: static/cves.txt
